export { Footer } from "./footer"
export { CashBoxList } from "./cashBoxList"
export { Modal } from "./modal"
export { InactiveForWhile } from "./modal/inactiveForWhile"
export { Confirm } from "./modal/confirm"
export { Prompt } from "./modal/prompt"
export { Info } from "./modal/info-kassa"
export { FooterMobile } from "./modal/footer-mobile"
